package com.example.tudursvehiclemod.asset;

import java.util.List;

/** Full configuration for a WeaponType.CARRIER weapon - a "launch a carrier aircraft" weapon: firing it marks a ground point (same crosshair-raycast idea CAS already uses) which serves as the route's own relative-coordinate center, spawns the vehicle named aircraftFileName at THIS weapon's own AddWeapon mount position (unlike CAS, which spawns at the route's own first waypoint - a carrier aircraft launches from the firing vehicle itself), and sends it flying the configured route, firing weaponIndex while passing through attack=true waypoints - largely reusing CAS's own tudursvehiclemod$updateCasAutoFire()/tudursvehiclemod$updateDroneWaypointAutopilot() mechanics. Unlike CAS, a player can seat-switch (Alt+Y) between the firing vehicle and this launched aircraft while it's airborne (see entity.AbstractVehicleEntity's own tudursvehiclemod$toggleCarrierSeat() doc), and reaching the route's own last waypoint begins a return-to-base landing sequence instead of despawning outright (see entity.AircraftEntity's own tudursvehiclemod$updateCarrierReturnToBase() doc). accuracy/timeoutTicks/stuckTimeoutTicks mean exactly what they mean for CasStrikeConfig's own same-named fields.
 *
 * THREE separate yaw corrections exist, 
 * - yawOffsetDegrees (CarrierYawOffset): a broad correction applied to BOTH the waypoint route's own rotation basis (the shooter's own forward direction, same as CAS's own yawOffsetDegrees) AND the landing approach direction (see tudursvehiclemod$updateCarrierReturnToBase()'s own doc) - deliberately affects everything except launch spawn yaw (which is handled entirely by the mothership's own AddWeapon "DefaultYaw" and needs no correction of its own at all).
 * - landingYawOffsetDegrees (CarrierLandingYawOffset): an ADDITIONAL correction applied ONLY to the landing approach direction - stacks on top of yawOffsetDegrees, for cases where landing needs independent fine-tuning without also shifting the waypoint route's own rotation.
 * - targetYawOffsetDegrees (CarrierTargetYawOffset): an ADDITIONAL correction applied ONLY to the waypoint route's own rotation - stacks on top of yawOffsetDegrees, for cases where the route needs independent fine-tuning without also shifting the landing approach angle.
 *
 * Parsed from a weapon.txt file's own "CarrierAircraft"/"CarrierWeaponIndex"/"CarrierAccuracy"/"CarrierTimeout"/"CarrierStuckTimeout"/"CarrierYawOffset"/"CarrierLandingYawOffset"/"CarrierTargetYawOffset"/repeated "CarrierWaypoint"/repeated "CarrierLaunchWaypoint"/repeated "CarrierLandingWaypoint" lines (see WeaponStatsLoader's own parsing doc) - waypoint lines reuse CasWaypoint's own "relX,relY,relZ,speedPercent,attack" line format unchanged. launchWaypoints are a SEPARATE, dedicated liftoff route flown FIRST (prepended to waypoints as one combined route at launch time) - lets a carrier aircraft follow a distinct, scripted departure path off the flight deck before joining its own normal patrol/strike route.
 *
 * FormationSize/formationType/formationSpacing - launches formationSize aircraft instead of just one, from the SAME mount position (a carrier launches sequentially from one spot, not several) - the formation offset applies only to waypoints (the patrol/strike route), NOT launchWaypoints (the scripted liftoff path, deliberately unaffected so every aircraft clears the deck identically before diverging into formation). Aircraft index 0 is always the lead (a zero offset - unmodified route, matching the original single-aircraft behavior exactly). formationSize 1 (the default, keys absent) means no formation at all. Parsed from "CarrierFormationSize"/"CarrierFormationType"/"CarrierFormationSpacing".
 *
 * ElementSpacing - for FormationType.DIAMOND/DELTA only, the distance (blocks) between element CENTROIDS, independently configurable from formationSpacing (which, for these two types, instead governs spacing between aircraft WITHIN the same element). Empty (the default, key absent) falls back to AbstractVehicleEntity's own auto-derived value (elementSize*1.5x formationSpacing). Parsed from "CarrierFormationElementSpacing".
 *
 * Stage 3-4 additions, 
 * - the RUNWAY itself moved OUT of this weapon-level config entirely and onto VehicleDefinition's own runway field (RunwayDefinition, in the mothership's own vehicle.json) - a weapon-tied runway lacked flexibility (varying it per-mothership needed a separate, otherwise-duplicate weapon file; a ship without any Carrier weapon at all couldn't have a runway to land other aircraft on either). A runway is a property of the SHIP itself, not of any one weapon slot on it.
 * - landingToAmmoRadius (CarrierLandingToAmmoRadius, default 15.0, relaxing recovery conditions): any player-piloted aircraft (not just ones this Carrier weapon itself launched) matching aircraftFileName within this radius of the CURRENT AddWeapon position (no velocity/"stationary" requirement - matches the same purely position-based condition the autonomous return-to-base sequence itself already uses), and MaxAmmo has room for it, gets silently converted into +1 ammo (exactly like a successful return-to-base landing) - see entity.AbstractVehicleEntity's own tudursvehiclemod$updateCarrierLandingToAmmo() doc. That same method's own in-flight-count exclusion (whether a tracked aircraft counts as "still out there" vs "essentially already landed") uses this exact radius too, paired with a 10 km/h speed threshold. This AddWeapon-centered zone is always active regardless of extraRecoveryPoints below - it's the original, unconditional recovery zone, not one this record can disable.
 * - extraRecoveryPoints (repeated "CarrierRecoveryPoint" lines, letting a carrier offer additional recovery zones beyond the single AddWeapon-centered one above - e.g. a second landing spot/elevator elsewhere on the deck): each is its own independent ship-local point (the same rotated reference frame as the landing approach point - relative to THIS weapon's own AddWeapon position, following the mothership's own current facing, via entity.AbstractVehicleEntity's own tudursvehiclemod$carrierLocalToWorld()) plus its own independently-configured radius - see entity.AbstractVehicleEntity's own tudursvehiclemod$updateCarrierLandingToAmmo() doc for exactly how every zone (the AddWeapon-centered one AND each of these) is checked together. Empty (the default) means no additional zones - only the original AddWeapon-centered one is active, unchanged from before this field existed.
 * - landingWaypoints (repeated "CarrierLandingWaypoint" lines, same format/record type as launchWaypoints - CarrierLaunchWaypoint, gear/bay triggers included) - REQUIRED (at least one), flown in order once this aircraft's own return-to-base leg begins. Ship-relative (same rotated reference frame the old approach point used, recomputed every tick from the mothership's own CURRENT position/yaw - unlike launchWaypoints, which only need computing once at spawn since the aircraft departs immediately, a landing approach can span many seconds during which the mothership may still be moving/turning). The LAST waypoint in this list takes over the old approach point's own exact role (the anchor for the final straight-line approach into AddWeapon itself) - see entity.AircraftEntity's own tudursvehiclemod$updateCarrierReturnToBase() doc for exactly how these are flown.
 *
 * An earlier "board a fixed ship-local point within 3 blocks, then accelerate gradually (per-tick) toward a configured launch speed" mechanic (CarrierCatapultConfig/CarrierCatapultX-Z/Acceleration/LaunchSpeed) was scaffolded (config parsing existed) but never actually implemented (its own tudursvehiclemod$tryUseCatapult() behavior method was never written) - removed entirely rather than finished, since it depended on player boarding (incompatible with this weapon type's own fully-autonomous Stage 1 launch flow) and has been superseded by CarrierLaunchWaypoint's own speedBoostKmh field instead (an instant, waypoint-triggered speed snap flown as part of the normal launch route, rather than a separate boardable point with its own gradual ramp-up) - see that field's own doc for the actual, current catapult mechanic. */
public record CarrierAircraftConfig(String aircraftFileName, int weaponIndex, float accuracy, int timeoutTicks, int stuckTimeoutTicks, float yawOffsetDegrees, float landingYawOffsetDegrees, float targetYawOffsetDegrees, List<CarrierLaunchWaypoint> launchWaypoints, List<CasWaypoint> waypoints,
                                      double landingToAmmoRadius, List<CarrierRecoveryPointConfig> extraRecoveryPoints, List<CarrierLaunchWaypoint> landingWaypoints,
                                      int formationSize, FormationType formationType, double formationSpacing, double elementSpacing) {

	/** See CarrierAircraftConfig's own extraRecoveryPoints doc. x/y/z are ship-local, relative to this weapon's own AddWeapon position, same rotated reference frame as the landing approach point (and as the old catapult point used to be). radius is this specific zone's own independent recovery radius - deliberately NOT shared with landingToAmmoRadius (the AddWeapon-centered zone's own radius) or with each other, since different physical recovery spots on a large deck (e.g. a side elevator vs. the main landing area) may reasonably need different capture sizes. Parsed from a repeated "CarrierRecoveryPoint = relX,relY,relZ,radius" line - all four columns required (unlike CarrierLaunchWaypoint's own trailing-optional columns, there's no sensible partial/default form for a recovery point). */
	public record CarrierRecoveryPointConfig(double x, double y, double z, double radius) {

		/** Parses one "CarrierRecoveryPoint" line's own value (everything after "=") - returns null (caller should warn and skip) if malformed (wrong column count, or any column isn't a valid number), same defensive convention as CarrierLaunchWaypoint's own tudursvehiclemod$parse(). */
		public static CarrierRecoveryPointConfig tudursvehiclemod$parse(String line) {
			String[] parts = line.split(",", -1);
			if (parts.length != 4) {
				return null;
			}
			try {
				return new CarrierRecoveryPointConfig(
						Double.parseDouble(parts[0].trim()), Double.parseDouble(parts[1].trim()),
						Double.parseDouble(parts[2].trim()), Double.parseDouble(parts[3].trim()));
			} catch (NumberFormatException e) {
				return null;
			}
		}
	}
}
